In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import v_measure_score

In [ ]:
db = np.genfromtxt('dados/data/wineRed-train.csv', delimiter=',')

,7.4,0.64,0.17,5.4,0.168,52,98,0.99736,3.28,0.5,9.5,5
0,10.4,0.440,0.73,6.55,0.074,38.0,76.0,0.99900,3.17,0.85,12.0,7
1,10.7,0.430,0.39,2.20,0.106,8.0,32.0,0.99860,2.89,0.50,9.6,5
2,8.9,0.635,0.37,1.70,0.263,5.0,62.0,0.99710,3.00,1.09,9.3,5
3,7.8,0.570,0.09,2.30,0.065,34.0,45.0,0.99417,3.46,0.74,12.7,8
4,12.0,0.370,0.76,4.20,0.066,7.0,38.0,1.00040,3.22,0.60,13.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...
1273,11.4,0.460,0.50,2.70,0.122,4.0,17.0,1.00060,3.13,0.70,10.2,5
1274,9.4,0.410,0.48,4.60,0.072,10.0,20.0,0.99730,3.34,0.79,12.2,7
1275,6.9,0.540,0.04,3.00,0.077,7.0,27.0,0.99870,3.69,0.91,9.4,6
1276,8.9,0.610,0.49,2.00,0.270,23.0,110.0,0.99720,3.12,1.02,9.3,5
1277,7.3,0.980,0.05,2.10,0.061,20.0,49.0,0.99705,3.31,0.55,9.7,3

In [ ]:
clustering = AgglomerativeClustering(metric="precomputed", linkage="average").fit(dmx)
labels_pred = clustering.labels_

v = v_measure_score(labels_true, labels_pred)

In [8]:
np.random.choice(['0', '1'], 10).flatten().shape

(10,)